#!/usr/bin/env python3

import sys, cgi, json, cgitb
import pandas as pd
from sqlalchemy import create_engine
from datetime import datetime

cgitb.enable()

# start new stuff 
page_data = cgi.FieldStorage()

print("Content-type: text/html\n\n")
# print(page_data.keys())

data = json.loads(page_data.getvalue("data"))

print(data['type'])




